[package]
name = "xrmp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
colored = "2.1.0"
reqwest = { version = "0.12.5", features = ["blocking", "json"] } 
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0"
toml = "0.8.16"